// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgCYuMz9HKO2ZyQftk9s18gEocUyzGzNQ',
    appId: '1:400881331308:web:61d32c13d81e219b70fc49',
    messagingSenderId: '400881331308',
    projectId: 'skladhelper',
    authDomain: 'skladhelper.firebaseapp.com',
    storageBucket: 'skladhelper.firebasestorage.app',
    measurementId: 'G-G9DDGKM3LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscl-cMrEIGQzt19GJ-vhTv88PLfwR-fs',
    appId: '1:400881331308:android:359884a38cb7c85570fc49',
    messagingSenderId: '400881331308',
    projectId: 'skladhelper',
    storageBucket: 'skladhelper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXs46cTFSzjQUhu_8cUsoSflBqckTJWVE',
    appId: '1:400881331308:ios:f3c5399b1061a08a70fc49',
    messagingSenderId: '400881331308',
    projectId: 'skladhelper',
    storageBucket: 'skladhelper.firebasestorage.app',
    iosBundleId: 'com.example.skladHelper',
  );
}
